version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu
    overwrite: yes
file_exists_behavior: OVERWRITE
hooks:
  ApplicationStop:
    - location: scripts/stop_container.sh
      timeout: 60
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_container.sh
      timeout: 60
      runas: ubuntu
