---

- name: Team1 Codedeploy Role
  hosts: localhost
  gather_facts: no
  vars_files:
    - ./aws_key.yml

  tasks:
    - name: Create IAM Role
      iam_role:
        aws_access_key: "{{ access_key }}"
        aws_secret_key: "{{ secret_key }}"
        name: Team1-code-deploy-service-role
        assume_role_policy_document: "{{ lookup('file', 'codedeploy-policy.json') }}"
        state: present
        managed_policy:
          - arn:aws:iam::aws:policy/service-role/AWSCodeDeployRole
